### ISSUE TITLE
Use "luaossl" package?

### ISSUE THREAD

**Issue by cdbattags** [jkeys089/lua-resty-hmac#10]
I saw the deprecation warning at https://github.com/starius/luacrypto from a dependency of the old version of this lib and I'm curious what we can do to just get behind https://luarocks.org/modules/daurnimator/luaossl as the latest and greatest?

**Comment by jkeys089** [comment]
I'm not sure I understand what you're asking. I have nothing to do with luacrypto. I think if you wanted you may be able to use luaossl instead of lua-resty-hmac (again, though, I have nothing to do with that project).

If you're having a problem with lua-resty-hmac please let me know and I may be able to help. Sorry if I'm misunderstanding the issue here.

**Comment by cdbattags** [comment]
Note my comment from #9. I got extremely confused with the way https://github.com/zmartzone/lua-resty-openidc was adding dependencies and naming conflicts with the other `lua-resty-hmac` package found on LuaRocks. Sorry to bother!
